export const routes = {
   home: '/',
   signIn: '/sign-in',
   signUp: '/sign-up',
   lessons: '/lessons',
   repeat: '/repeat',
   profile: '/profile',
   singleLesson: '/lesson/:id',
   typing: '/lesson/:id/typing',
   quiz: '/lesson/:id/quiz',
   flashcards: '/lesson/:id/flashcards',
   test: '/lesson/:id/test',
   emailConfirm: '/emailconfirm',
   forgottenPassword: '/forgotten-password',
   sendNewPassword: '/reset_password',
};
